services:
  postgres:
    image: postgres:16-alpine
    container_name: webrik_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webrik_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webrik_app
    restart: always
    ports:
      - "127.0.0.1:3022:3022"
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@postgres:5432/webrik_db
      - PAYLOAD_SECRET=webrik_super_secret_payload_jwt_key_2026
      - PORT=3022
      - NEXT_PUBLIC_SITE_URL=http://localhost:3022
      - NEXT_PUBLIC_SERVER_URL=http://localhost:3022
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
