/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    services: Service;
    industries: Industry;
    projects: Project;
    'case-studies': CaseStudy;
    'blog-posts': BlogPost;
    'blog-categories': BlogCategory;
    authors: Author;
    clients: Client;
    testimonials: Testimonial;
    faqs: Faq;
    technologies: Technology;
    'team-members': TeamMember;
    jobs: Job;
    'contact-submissions': ContactSubmission;
    redirects: Redirect;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'seo-settings': SeoSetting;
    'analytics-settings': AnalyticsSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'seo-settings': SeoSettingsSelect<false> | SeoSettingsSelect<true>;
    'analytics-settings': AnalyticsSettingsSelect<false> | AnalyticsSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use "home" for the main homepage route (/). Use "about", "contact", "careers", "privacy-policy", "terms-and-conditions", etc.
   */
  slug: string;
  layout?:
    | (
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            primaryCTA?: {
              label?: string | null;
              url?: string | null;
              variant?: ('primary' | 'secondary' | 'outline' | 'link') | null;
              openInNewTab?: boolean | null;
            };
            secondaryCTA?: {
              label?: string | null;
              url?: string | null;
              variant?: ('primary' | 'secondary' | 'outline' | 'link') | null;
              openInNewTab?: boolean | null;
            };
            techBadgeList?:
              | {
                  badgeText?: string | null;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBlock';
          }
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            heading?: string | null;
            selectMode?: ('all' | 'custom') | null;
            clients?: (number | Client)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoCloudBlock';
          }
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            filterCategory?: ('all' | 'software' | 'marketing') | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesGridBlock';
          }
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            heading?: string | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  sublabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsBlock';
          }
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            eyebrow?: string | null;
            heading?: string | null;
            content?: string | null;
            cta?: {
              label?: string | null;
              url?: string | null;
              variant?: ('primary' | 'secondary' | 'outline' | 'link') | null;
              openInNewTab?: boolean | null;
            };
            pillars?:
              | {
                  title?: string | null;
                  description?: string | null;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutBlock';
          }
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'industriesGridBlock';
          }
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            eyebrow?: string | null;
            heading?: string | null;
            limit?: number | null;
            showFilter?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'portfolioGridBlock';
          }
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            eyebrow?: string | null;
            heading?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'caseStudiesBlock';
          }
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            eyebrow?: string | null;
            heading?: string | null;
            steps?:
              | {
                  stepNumber: string;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'processBlock';
          }
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            eyebrow?: string | null;
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsBlock';
          }
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            eyebrow?: string | null;
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'teamBlock';
          }
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            eyebrow?: string | null;
            heading?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blogGridBlock';
          }
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            eyebrow?: string | null;
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            heading?: string | null;
            subheading?: string | null;
            primaryCTA?: {
              label?: string | null;
              url?: string | null;
              variant?: ('primary' | 'secondary' | 'outline' | 'link') | null;
              openInNewTab?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            heading?: string | null;
            subheading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactBlock';
          }
        | {
            blockVisibility?: {
              hidden?: boolean | null;
              anchorId?: string | null;
              customClassName?: string | null;
            };
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextBlock';
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  website?: string | null;
  industry?: string | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  category: 'software' | 'marketing';
  icon?: string | null;
  shortDescription: string;
  fullContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  features?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  deliverables?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  processSteps?:
    | {
        step?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedProjects?: (number | Project)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  clientName: string;
  category: 'Web Development' | 'Mobile App' | 'E-commerce' | 'SaaS' | 'Branding' | 'Digital Marketing';
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  shortDescription: string;
  fullContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  technologies?: (number | Technology)[] | null;
  liveUrl?: string | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: number;
  name: string;
  category?: ('frontend' | 'backend' | 'mobile' | 'cloud' | 'marketing') | null;
  icon?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  name: string;
  slug: string;
  icon?: string | null;
  shortDescription: string;
  heroImage?: (number | null) | Media;
  challenges?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  solutions?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedServices?: (number | Service)[] | null;
  caseStudies?: (number | CaseStudy)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  client: string;
  industry?: (number | null) | Industry;
  heroImage?: (number | null) | Media;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  challenge: string;
  solution: string;
  implementationDetails?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  technologies?: (number | Technology)[] | null;
  testimonialQuote?: string | null;
  testimonialAuthor?: string | null;
  featured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  author: number | Author;
  category: number | BlogCategory;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedDate?: string | null;
  readingTime?: string | null;
  featured?: boolean | null;
  status?: ('draft' | 'published') | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  role?: string | null;
  avatar?: (number | null) | Media;
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  clientName: string;
  designation: string;
  company: string;
  photo?: (number | null) | Media;
  rating?: number | null;
  testimonial: string;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: ('general' | 'software' | 'marketing' | 'pricing') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  designation: string;
  photo?: (number | null) | Media;
  bio?: string | null;
  linkedIn?: string | null;
  skills?:
    | {
        skill?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  slug: string;
  department: 'Engineering' | 'Digital Marketing' | 'Design' | 'Sales';
  location?: string | null;
  employmentType?: ('Full-time' | 'Part-time' | 'Contract') | null;
  experience?: string | null;
  description: string;
  responsibilities?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  service?: string | null;
  budget?: ('Under ₹1 Lakh' | '₹1–5 Lakh' | '₹5–10 Lakh' | '₹10–25 Lakh' | '₹25 Lakh+') | null;
  message: string;
  status?: ('new' | 'contacted' | 'in_progress' | 'closed') | null;
  crmNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  statusCode?: ('301' | '302') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: ('admin' | 'marketing_manager' | 'editor' | 'author')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'technologies';
        value: number | Technology;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        heroBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              eyebrow?: T;
              heading?: T;
              description?: T;
              primaryCTA?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    openInNewTab?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    openInNewTab?: T;
                  };
              techBadgeList?:
                | T
                | {
                    badgeText?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoCloudBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              heading?: T;
              selectMode?: T;
              clients?: T;
              id?: T;
              blockName?: T;
            };
        servicesGridBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              eyebrow?: T;
              heading?: T;
              description?: T;
              filterCategory?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        statsBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              heading?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    sublabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        aboutBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              eyebrow?: T;
              heading?: T;
              content?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    openInNewTab?: T;
                  };
              pillars?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        industriesGridBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              eyebrow?: T;
              heading?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        portfolioGridBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              eyebrow?: T;
              heading?: T;
              limit?: T;
              showFilter?: T;
              id?: T;
              blockName?: T;
            };
        caseStudiesBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              eyebrow?: T;
              heading?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        processBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              eyebrow?: T;
              heading?: T;
              steps?:
                | T
                | {
                    stepNumber?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonialsBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              eyebrow?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        teamBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              eyebrow?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        blogGridBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              eyebrow?: T;
              heading?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              eyebrow?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              heading?: T;
              subheading?: T;
              primaryCTA?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    openInNewTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              heading?: T;
              subheading?: T;
              id?: T;
              blockName?: T;
            };
        richTextBlock?:
          | T
          | {
              blockVisibility?:
                | T
                | {
                    hidden?: T;
                    anchorId?: T;
                    customClassName?: T;
                  };
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  icon?: T;
  shortDescription?: T;
  fullContent?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  deliverables?:
    | T
    | {
        item?: T;
        id?: T;
      };
  processSteps?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  relatedProjects?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  shortDescription?: T;
  heroImage?: T;
  challenges?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  solutions?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  relatedServices?: T;
  caseStudies?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  clientName?: T;
  category?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  shortDescription?: T;
  fullContent?: T;
  technologies?: T;
  liveUrl?: T;
  featured?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  industry?: T;
  heroImage?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  challenge?: T;
  solution?: T;
  implementationDetails?: T;
  technologies?: T;
  testimonialQuote?: T;
  testimonialAuthor?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedDate?: T;
  readingTime?: T;
  featured?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  industry?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  designation?: T;
  company?: T;
  photo?: T;
  rating?: T;
  testimonial?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  designation?: T;
  photo?: T;
  bio?: T;
  linkedIn?: T;
  skills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  department?: T;
  location?: T;
  employmentType?: T;
  experience?: T;
  description?: T;
  responsibilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        item?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        item?: T;
        id?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  service?: T;
  budget?: T;
  message?: T;
  status?: T;
  crmNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  contactPhone?: string | null;
  contactEmail?: string | null;
  address?: string | null;
  socialLinks?: {
    linkedIn?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    github?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  announcementText?: string | null;
  navItems?:
    | {
        label: string;
        url: string;
        hasMegaMenu?: boolean | null;
        megaMenuType?: ('services' | 'industries') | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    url?: string | null;
    variant?: ('primary' | 'secondary' | 'outline' | 'link') | null;
    openInNewTab?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  description?: string | null;
  serviceLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  companyLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings".
 */
export interface SeoSetting {
  id: number;
  titleTemplate?: string | null;
  defaultMetaDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  twitterHandle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings".
 */
export interface AnalyticsSetting {
  id: number;
  googleAnalyticsId?: string | null;
  googleTagManagerId?: string | null;
  metaPixelId?: string | null;
  customHeadScripts?: string | null;
  customBodyScripts?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  contactPhone?: T;
  contactEmail?: T;
  address?: T;
  socialLinks?:
    | T
    | {
        linkedIn?: T;
        twitter?: T;
        instagram?: T;
        github?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  announcementText?: T;
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        hasMegaMenu?: T;
        megaMenuType?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        variant?: T;
        openInNewTab?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  serviceLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  companyLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings_select".
 */
export interface SeoSettingsSelect<T extends boolean = true> {
  titleTemplate?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  twitterHandle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings_select".
 */
export interface AnalyticsSettingsSelect<T extends boolean = true> {
  googleAnalyticsId?: T;
  googleTagManagerId?: T;
  metaPixelId?: T;
  customHeadScripts?: T;
  customBodyScripts?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}